services:
  cache.factory.apcu:
    class: Cache\AdapterBundle\Factory\ApcuFactory
  cache.factory.array:
    class: Cache\AdapterBundle\Factory\ArrayFactory
  cache.factory.chain:
    class: Cache\AdapterBundle\Factory\ChainFactory
  cache.factory.filesystem:
    class: Cache\AdapterBundle\Factory\FilesystemFactory
  cache.factory.fallback:
    class: Cache\AdapterBundle\Factory\FallbackAdapterFactory
  cache.factory.memcached:
    class: Cache\AdapterBundle\Factory\MemcachedFactory
  cache.factory.memcache:
    class: Cache\AdapterBundle\Factory\MemcacheFactory
  cache.factory.mongodb:
    class: Cache\AdapterBundle\Factory\MongoDBFactory
  cache.factory.namespaced:
    class: Cache\AdapterBundle\Factory\NamespacedFactory
  cache.factory.predis:
    class: Cache\AdapterBundle\Factory\PredisFactory
  cache.factory.prefixed:
    class: Cache\AdapterBundle\Factory\PrefixedFactory
  cache.factory.redis:
    class: Cache\AdapterBundle\Factory\RedisFactory
  cache.factory.void:
    class: Cache\AdapterBundle\Factory\VoidFactory
